name: 'Bright Stop Discovery'
description: 'Stops Bright Discovery'
branding:
  icon: stop-circle
  color: blue
inputs:
  api_token:
    description: 'Api Token. You can generate it in Organization section'
    required: true
  discovery:
    description: 'Discovery ID to wait for'
    required: true
  project:
    description: 'ID of the project that the discovery belongs to'
  hostname:
    description: 'Hostname. Default is app.brightsec.com'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
